import 'package:riverpod_annotation/riverpod_annotation.dart';
import '../data/academy_repository.dart';
import '../domain/academy.dart';

part 'academy_controller.g.dart';

@riverpod
Stream<List<Academy>> academiesStream(Ref ref) {
  return ref.watch(academyRepositoryProvider).watchAcademies();
}

@riverpod
class AcademyController extends _$AcademyController {
  @override
  FutureOr<void> build() {}

  Future<void> createAcademy({
    required String name,
    required String address,
    required String contact,
    required String principalEmail,
    required String principalPassword,
  }) async {
    state = const AsyncValue.loading();
    state = await AsyncValue.guard(() async {
      final repository = ref.read(academyRepositoryProvider);
      final academy = Academy(
        id: '', // Will be generated by repository
        name: name,
        address: address,
        contact: contact,
      );
      await repository.createAcademy(academy, principalEmail, principalPassword);
    });
  }

  Future<void> updateAcademy(Academy academy) async {
    state = const AsyncValue.loading();
    state = await AsyncValue.guard(() async {
      await ref.read(academyRepositoryProvider).updateAcademy(academy);
    });
  }

  Future<void> deleteAcademy(String id) async {
    state = const AsyncValue.loading();
    state = await AsyncValue.guard(() async {
      await ref.read(academyRepositoryProvider).deleteAcademy(id);
    });
  }

  Future<void> toggleAcademyStatus(Academy academy) async {
    state = const AsyncValue.loading();
    state = await AsyncValue.guard(() async {
      final newStatus = academy.status == AcademyStatus.active
          ? AcademyStatus.disabled
          : AcademyStatus.active;
      await ref.read(academyRepositoryProvider)
          .updateAcademy(academy.copyWith(status: newStatus));
    });
  }
}
